# Generated by Django 4.1.13 on 2024-04-20 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_signin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signin',
        ),
    ]
